### ISSUE TITLE
Could not save messages.yml - already exists

### ISSUE THREAD

**Issue by smmmadden** [Haileykins/AutoBroadcasterPlus#2]
Spigot 1.13 built 15 minutes ago (11-AUG-18).
AutoBroadcasterPlus tried both 1.0 and 1.3
Startup has warning about messages.yml file already existing
[21:57:18 WARN]: [AutoBroadcasterPlus] Could not save messages.yml to plugins\AutoBroadcasterPlus\messages.yml because messages.yml already exists.

**Comment by Haileykins** [comment]
This is the first run of the plugin you say? If it's not the first run and the folder is still there with the messages file in it it will put that in the console just to announce that it will not be creating one for the server.

Also, so sorry I haven't seen this sooner, Github wasn't emailing me!

**Comment by smmmadden** [comment]
no worries.  This is on server startup - every time.  There should be a check to skip updating it if there are no updates or if it already exists.  That would be more appropriate I think to get rid of the noise.

**Comment by Haileykins** [comment]
Found out the issue was actually not corrected, I corrected the issue on the config file which didn't have this issue.
