### ISSUE TITLE
Autobroadcast - repeating broadcast msgs - no order

### ISSUE THREAD

**Issue by smmmadden** [Haileykins/AutoBroadcasterPlus#5]
While the broadcaster is working, it appears to be using a randomizer for each of the messages, but it also means they are repeating too soon as shown in my chat window.
![image](https://user-images.githubusercontent.com/10309346/44997457-73e51a80-af7c-11e8-99d6-e6342ec8ea2f.png)
![image](https://user-images.githubusercontent.com/10309346/44997464-895a4480-af7c-11e8-8dc1-18bf2d72db1b.png)

What would be helpful is to add another parameter that states the sort order number (e.g. **sortOrder:** 1, 2, 3 etc or 0 for random sort)
The sortOrder would provide exact sorting for broadcasting for each server.  I could have welcome, jobsstats, voting as 1,2,3 and 4-7 for the others.
Another option would be to add a parameter one level up.
messages:
**sortBy:** (fileorder, alphanumericASC, alphanumericDESC, random) - with random as default

Thanks! -Steve

**Comment by smmmadden** [comment]
@Haileykins - just checking in to see if you'll be able to update this plugin for 1.13.1?

**Comment by Haileykins** [comment]
This plugin will work 100% with 1.13.x as it does not use any code that has changed in 1.13.x, I have added the enhancement tag as something to do and will definitely consider this as an addition on the next update (I'm currently working for a server and just got a new truck, so I have been a bit busy).

Sorry for this reply coming so late, GitHub has not been notifying me of new issues etc.

In the meantime to prevent the messages from spamming your chat like that, there is an option that is a chat interval feature that won't broadcast a message until enough messages are sent to reset the counter and let it broadcast again. For example, if you set the chat message interval to 10 it will wait until ten messages have been sent in chat before it will broadcast again. Its set to 0 by default.

**Comment by smmmadden** [comment]
Thanks Haileykins, I had a feeling that it was a notification issue so I always follow up just in case. :-)
If I change the Chat-Interval: 1 or higher then I see no broadcast messages.  Even with an /abc reload or /abc reboot
I tested the /abc cast myMessage and that works fine.  Is it possible that the                         **player.spigot().sendMessage(msg);** code is not working for PaperSpigot and only working for Spigot when the interval is changed?

**Comment by smmmadden** [comment]
Hi - yes I do.  Feel free to connect to me here: https://discord.gg/NGWzDP
